ci: checkpatch: Replace python-git to python-git-doc
Checkpatch was failing for Azure. This is the error and the fix:

Package python-git is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source
However the following packages replace it:
  python-git-doc

E: Package 'python-git' has no installation candidate
Error: Process completed with exit code 100.

Signed-off-by: Mircea Caprioru <mircea.caprioru@analog.com>
(cherry picked from commit 7488ca258575e186937eb5183de1b4fd02da8bb3)